### ISSUE TITLE
File google-services.json is missing

### ISSUE THREAD

**Issue by tonyyang924** [7a6ac0/GYAP#1]
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/tonyyang/Documents/Github/GYAP/app/src/nullnull/debug/google-services.json
  /Users/tonyyang/Documents/Github/GYAP/app/src/debug/nullnull/google-services.json
  /Users/tonyyang/Documents/Github/GYAP/app/src/nullnull/google-services.json
  /Users/tonyyang/Documents/Github/GYAP/app/src/debug/google-services.json
  /Users/tonyyang/Documents/Github/GYAP/app/src/nullnullDebug/google-services.json
  /Users/tonyyang/Documents/Github/GYAP/app/google-services.json

**Comment by 7a6ac0** [comment]
Hi @tonyyang924,
你必須要去 [firebase](https://firebase.google.com/) 申請產生自己的google-services.json才行。

**Comment by tonyyang924** [comment]
@7a6ac0 了解，所以放置自己的google-services.json也可以! 謝謝
